FROM public.ecr.aws/ubuntu/ubuntu:18.04 AS base

ENV UBUNTU_CODENAME=bionic
ENV DEBIAN_FRONTEND=nonintercative
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Use local Ubuntu sources if necessary
# COPY source_mirrors/aliyun_sources_bionic.list /etc/apt/sources.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg dirmngr ca-certificates git wget unzip curl \
    build-essential cmake \
    `# Pangolin deps` libgl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols libegl1-mesa-dev libc++-dev libglew-dev libeigen3-dev \
    `# OpenCV required deps` libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
    # `# OpenCV optional deps` python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


FROM base AS pangolin

RUN git clone --depth 1 --branch v0.5 https://github.com/stevenlovegrove/Pangolin.git

RUN cd Pangolin && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install


FROM base AS opencv

ENV OPENCV_VERSION=3.4.16

RUN curl -L0 https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip > ${OPENCV_VERSION}.zip && \
    unzip ${OPENCV_VERSION}.zip

RUN cd opencv-${OPENCV_VERSION} && \
    mkdir build && \
    cd build && \
    cmake -D CMAKE_BUILD_TYPE=Release –D CMAKE_INSTALL_PREFIX=/usr/local .. && \
    make && \
    make install

FROM base AS orb-slam2

COPY --from=pangolin /usr/local /usr/local

COPY --from=opencv /usr/local /usr/local

# ENV ROS_MIRROR_URL=http://packages.ros.org/ros/ubuntu
# ENV ROS_MIRROR_URL=http://mirrors.sjtug.sjtu.edu.cn/ros/ubuntu

#RUN echo "deb ${ROS_MIRROR_URL} ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/ros-latest.list \
#    && apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
#
#RUN apt-get update && apt-get install -y --no-install-recommends \
#    ros-melodic-desktop \
#    && apt-get clean && rm -rf /var/lib/apt/lists/*

